import { SchemaObject } from 'openapi3-ts';
import { getMetadataArgsStorage } from 'routing-controllers';
import { routingControllersToSpec } from 'routing-controllers-openapi';
import { validationMetadatasToSchemas } from 'class-validator-jsonschema';

export class SwaggerSetup {
  static classValidatorSchema: Record<string, SchemaObject>;

  public static getSwaggerAutoGeneratedSchema() {
    this.classValidatorSchema = validationMetadatasToSchemas({
      refPointerPrefix: '#/components/schemas/',
    });

    const metaDataArgsStorage = getMetadataArgsStorage();

    const autoGeneratedSwaggerDoc = routingControllersToSpec(
      metaDataArgsStorage,
      {},
      { components: { schemas: this.classValidatorSchema } },
    );
    return autoGeneratedSwaggerDoc;
  }
}
